FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom config
COPY default.conf /etc/nginx/conf.d/

# Copy frontend files
COPY index.html /usr/share/nginx/html/index.html
COPY login.html /usr/share/nginx/html/login.html
COPY signup.html /usr/share/nginx/html/signup.html
COPY dashboard.html /usr/share/nginx/html/dashboard.html
COPY balance.html /usr/share/nginx/html/balance.html
COPY transactions.html /usr/share/nginx/html/transactions.html
COPY login.js /usr/share/nginx/html/login.js
COPY signup.js /usr/share/nginx/html/signup.js
