apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-bank
  template:
    metadata:
      labels:
        app: backend-bank
    spec:
      containers:
        - name: backend
          image: vamshipanjala/backend-bank:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql-bank-service
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: bankdb
---
apiVersion: v1
kind: Service
metadata:
  name: backend-bank-service
spec:
  selector:
    app: backend-bank
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
