apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-bank
  template:
    metadata:
      labels:
        app: frontend-bank
    spec:
      containers:
        - name: frontend
          image: vamshipanjala/frontend-bank:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-bank-service
spec:
  selector:
    app: frontend-bank
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
