apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-bank
  template:
    metadata:
      labels:
        app: mysql-bank
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Vamsi321
            - name: MYSQL_DATABASE
              value: bankdb
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin123
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}

---

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-bank-service
spec:
  selector:
    app: mysql-bank
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
